Name:           ros-indigo-roch-safety-controller
Version:        1.0.11
Release:        0%{?dist}
Summary:        ROS roch_safety_controller package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/roch_safety_controller
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-ecl-threads
Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-roch-msgs
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-std-msgs
Requires:       ros-indigo-yocs-controllers
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-ecl-threads
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-roch-msgs
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-std-msgs
BuildRequires:  ros-indigo-yocs-controllers

%description
A controller ensuring the safe operation of roch. The SafetyController keeps
track of ult, psd and cliff events. In case of the first three, roch is
commanded to move back. This controller can be enabled/disabled. The safety
states (bumper pressed etc.) can be reset. WARNING: Dangerous! Refrence with
yujinrobot' kobuki.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Feb 07 2017 Carl <wzhang@softrobtech.com> - 1.0.11-0
- Autogenerated by Bloom

* Tue Jan 24 2017 Carl <wzhang@softrobtech.com> - 1.0.10-0
- Autogenerated by Bloom

* Sun Jan 22 2017 Marcus Liebhardt <marcus.liebhardt@yujinrobot.com> - 1.0.8-0
- Autogenerated by Bloom

* Sat Jan 21 2017 Marcus Liebhardt <marcus.liebhardt@yujinrobot.com> - 1.0.7-0
- Autogenerated by Bloom

* Fri Jan 20 2017 Marcus Liebhardt <marcus.liebhardt@yujinrobot.com> - 1.0.6-1
- Autogenerated by Bloom

* Fri Jan 20 2017 Marcus Liebhardt <marcus.liebhardt@yujinrobot.com> - 1.0.6-0
- Autogenerated by Bloom

